### PR TITLE
add zeromq support

### PR DESCRIPTION
**Pull request by sbuzonas**

### CODE REVIEW

**Comment by dzuelke** [comment]
Could you please rebuild this PR using the new package infrastructure (see #104), and with new extension and library versions? Thanks!

**Comment by alcalyn** [comment]
+1

**Comment by dannycoulombe** [comment]
Any plan on adding zmq to this buildpack?

**Comment by dzuelke** [comment]
Closing: the `zmq` extension is completely unmaintained, hasn't been updated in over four years (since early 2016, and the last tag on GitHub is from 2013), and has no releases that are compatible with PHP 7.2 or later.

**Pull request closed without merging**
