### PR TITLE
Don't block access to well-known URLs in the nginx config

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by dzuelke** [comment]
Could you update the HTTPD config as well please?

**Comment by stof** [comment]
AFAICT, the HTTPD config does not have this block rule

**Comment by dzuelke** [comment]
@stof `conf/apache2/heroku.conf` has a rule for it

**Comment by stof** [comment]
@dzuelke I updated the regexp for the Apache config as well. But I haven't tested whether Apache accepts it (I don't have projects using Apache on my machine to try such config, and my own heroku projects are using nginx)

**Comment by stof** [comment]
@dzuelke anything else to do on that one to get it merged ?

**Comment by stof** [comment]
Hello @dzuelke 
Is there any news about this PR ? The change has been implemented for Apache.

**Comment by dzuelke** [comment]
Needs tests ;) Maybe at least spin up an empty project and validate it works with Apache; I can take care of automated tests once you've verified it works for both web servers.

**Comment by stof** [comment]
@dzuelke anything missing before merging this ?

**Comment by dzuelke** [comment]
Thanks for helping with the changes, @stof :)

**Pull request closed without merging**
