### PR TITLE
Use the content-hash from the lock file rather than the hash

### PR DESCRIPTION
**Pull request by stof**
Nightly builds of composer are not generating the hash anymore in their lock file: https://github.com/composer/composer/commit/8313e8687756059ef318a01386de2e3b789cebdd

### CODE REVIEW

**Comment by dzuelke** [comment]
Thanks. I need to make a bunch of other adjustments then to ensure the minimum version is 1.0 (custom PHARs), and throw out a few associated old workarounds such as the stdout and stderr redirects.

**Comment by stof** [comment]
content-hash is generated in lock files since 1.0.0-alpha11. the change was done in September 2015: https://github.com/composer/composer/pull/4140

**Comment by dzuelke** [comment]
Yeah I know but some customers are still building with `composer.phar` files present that are older than that, so I need to add a version check (to the boot scripts as well), and then I can remove a bunch of `tail -n 1` workarounds for older Composers that would spit out "outdated dev version..." warnings.

**Comment by dzuelke** [comment]
Plus, there are a lot of projects out there that haven't been touched in a while and won't have that field, so their builds would then fail. I suppose the check should instead be for either of the two?

**Comment by stof** [comment]
Well, we could indeed check for one or the other, and use the one being available. I will change this

**Comment by stof** [comment]
@dzuelke updated

**Pull request merged**
