### PR TITLE
Bugfix: allow heroku/heroku-buildpack-php to be in composer.json require-dev

### PR DESCRIPTION
**Pull request by gboudreau**
When compiling using `bin/test-compile` (like Heroku CI does), or whenever composer installs the dev dependencies (you can do that by setting the `HEROKU_PHP_INSTALL_DEV` environment variable to something that doesn't contain `--no-dev`), allow `heroku/heroku-buildpack-php` to be listed in the composer.json' `require-dev` section.

### CODE REVIEW

**Comment by gboudreau** [comment]
Of note: I'm not getting  the `Re: heroku/heroku-buildpack-php - This package may only be used as a dependency in 'require-dev'!` error anymore, but Heroku CI setup stills fails with error 82. Not sure if this is related.

**Comment by dzuelke** [comment]
Thanks for this PR. I am currently working on a related change that installs the buildpack globally, outside the project tree, to avoid interference (it would still force-link the "boot scripts" as most folks have "`vendor/bin/…`" in their `Procfile`s).

Would that be a more forward-compatible fix, as it removes the underlying issue altogether?

**Comment by gboudreau** [comment]
@dzuelke yes, maybe. Not sure what the underlying issue really is. :)

**Comment by dzuelke** [comment]
I realized I never closed this issue after fixing it in 44ed2000

**Pull request closed without merging**
