### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GabrielGil**
Fix 'buildpacks' typo. ;)

### CODE REVIEW

**Comment by dzuelke** [comment]
No, `buildpacks:set` is correct. https://devcenter.heroku.com/articles/buildpacks

**Comment by GabrielGil** [comment]
Mmmmm I'm afraid the documentation is wrong as well. Did you try the command by yourself @dzuelke ?
screen shot 2015-10-22 at 17 09 10

**Comment by dzuelke** [comment]
Yes, I am sure, Gabriel, because I use that command pretty much every day:

```
$ heroku help buildpacks
Usage: heroku buildpacks

 display the buildpack_url(s) for an app

Examples:

 $ heroku buildpacks
 https://github.com/heroku/heroku-buildpack-ruby

Additional commands, type "heroku help COMMAND" for more details:

  buildpacks:add BUILDPACK_URL       #  add new app buildpack, inserting into list of buildpacks if neccessary
  buildpacks:clear                   #  clear all buildpacks set on the app
  buildpacks:remove [BUILDPACK_URL]  #  remove a buildpack set on the app
  buildpacks:set BUILDPACK_URL       #  set new app buildpack, overwriting into list of buildpacks if neccessary
```

Your toolbelt version is quite old, maybe you should run `heroku update` to get the latest version. Also, check `heroku plugins` to see if you have an old "buildpacks" plugin installed for some reason that conflicts with this feature.

**Comment by GabrielGil** [comment]
My bad. Apologies, and thanks for the patience. :D

**Pull request closed without merging**
