### PR TITLE
Integrate Codizy into PHP Buildpack

### PR DESCRIPTION
**Pull request by jocel1**
Hi,

We'd like to integrate Codizy and its prerequisites directly into the heroku buildpack.
Would it be possible ?

Thanks and regards,
  Jocelyn Fournier

### CODE REVIEW

**Comment by Shine-neko** [comment]
wow Squash your commits /o

**Comment by jocel1** [comment]
yes, I agree this is ugly, I was not used to git at this time :)

**Comment by danielstjules** [comment]
`https://www.codizy.com/` (referred to in the changes) is no longer active, and the github organization hasn't had any activity since 2014. I'm guessing this can be closed?

**Comment by jocel1** [comment]
Yes, the website doesn't exist anymore, so I have now closed this PR.

**Pull request closed without merging**
