### PR TITLE
Fix a typo in log messages

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by stof** [comment]
@dzuelke anything left before merging ?

**Comment by dzuelke** [comment]
Nope; already got it merged locally (to the `develop` branch) and will push it out together with some other updates tomorrow.

**Comment by paazmaya** [comment]
@dzuelke any updates on this? Would be curious to see what other PRs have got merged..

**Comment by dzuelke** [comment]
2a311f2a6aa24c3322730799e60f73050c84f86a

**Pull request closed without merging**
