### PR TITLE
Added extension ssh2

### PR DESCRIPTION
**Pull request by martijngastkemper**
I've created a script to compile the [PHP SSH2 extension](http://pecl.php.net/package/ssh2). It depends on [libssh2](http://www.libssh2.org/).

### CODE REVIEW

**Comment by stof** [comment]
@dzuelke any chance this could get merged ? The extension improvements are waiting for months

**Comment by auro1** [comment]
Status of this?

**Comment by martijngastkemper** [comment]
I've stopped using the ssh2 extension in favor of [phpseclib](https://github.com/phpseclib/phpseclib). With GMP enabled (added ````{"require": {"ext-gmp": "*"}```` to ````composer.json````) it's working very nice. On top of that with phpseclib it's possible to load keys as a string. SSH2 requires files to load keys. So it's easier to configure with ``heroku config``. I'm not going to change this PR to the new custom packages architecture.

**Comment by dzuelke** [comment]
Alright. I'll close it for now; someone else can pick it up anytime :)

**Pull request closed without merging**
