### PR TITLE
Anchor .php at the end of the filename

### PR DESCRIPTION
**Pull request by blongden**
Currently, this will rewrite *.phppppppp through fcgi. Unlikely, but surprisingly caused me an issue today :)

### CODE REVIEW

**Comment by dzuelke** [comment]
Does this prevent `index.php/pathinfo`?

**Comment by blongden** [comment]
Good point. Perhaps change to `\.php([\/\?]?.*)$`

Icky regex, though.

**Comment by blongden** [comment]
Oh and i'd need to test that...

**Comment by dzuelke** [comment]
Can you test it please?

`.php($|/)` should work too.

**Comment by dzuelke** [comment]
poke @blongden ? :)

**Comment by dzuelke** [comment]
(no longer an issue)

**Pull request closed without merging**
