### PR TITLE
v175

### PR DESCRIPTION
**Pull request by dzuelke**

### CODE REVIEW

**Comment by rflavien** [comment]
With this PR we figured out that our PHP buildpack were running with the python provided by the python buildpack.
Now all our builds are failing with `ImportError: No module named site`. If we remove python from our buildpacks, the builds works but our application can't run without it.
Do you know how we can handle it ?

**Comment by dzuelke** [comment]
Hi @rflavien, thanks for the heads up. Tracking in #412.

**Comment by dzuelke** [comment]
Fixed, @rflavien

**Comment by rflavien** [comment]
Awsome ! Thank you :)

**Pull request merged**
