### PR TITLE
v236

### PR DESCRIPTION
**Pull request by dzuelke**
Version bumps for PHP, extensions, and packages

GUS-W-13574137
GUS-W-13574138
GUS-W-13574139

### CODE REVIEW

**Comment by dzuelke** [comment]
Builds:
- https://github.com/heroku/heroku-buildpack-php/actions/runs/5589415772
- https://github.com/heroku/heroku-buildpack-php/actions/runs/5589420463

**Review by edmorley — COMMENTED** [review]
CI is failing (incl after a retrigger):
https://github.com/heroku/heroku-buildpack-php/actions/runs/5590120833/jobs/10221059356?pr=647#step:7:390

**Comment by dzuelke** [comment]
Re-builds:
- https://github.com/heroku/heroku-buildpack-php/actions/runs/5592112221
- https://github.com/heroku/heroku-buildpack-php/actions/runs/5592114724

**Review by edmorley — APPROVED** [review]

**Comment by dzuelke** [comment]
Package syncs:
- https://github.com/heroku/heroku-buildpack-php/actions/runs/5592634774
- https://github.com/heroku/heroku-buildpack-php/actions/runs/5592635922

**Pull request merged**
