### PR TITLE
Add twig.so extension

### PR DESCRIPTION
**Pull request by buschjost**
Add twig extension

### CODE REVIEW

**Comment by ceichinger** [comment]
+1

**Comment by mikelohmann** [comment]
+1

**Comment by djmattyg007** [comment]
@seb0zz because not everyone using this service is a Symfony2 developer?

**Comment by buschjost** [comment]
@djmattyg007 the extension would not not be enabled for everyone. It would only be available to be enabled by users. So it has no impact to users who do not want to use it. 
Also there are many more users and frameworks using twig than just Symfony2.

**Comment by seb0zz** [comment]
And even if only Symfony2 users would be using Twig? Symfony2 is one is the most used PHP frameworks and we are only talking about only giving the option to work with the Twig extension. It's not even that everyone HAS to use the extension. 

In fact it's the same with databases: Not everyone on the world uses MongoDB in their PHP Heroku projects but still they have the chance to enable the extension. Now Twig might not be such a critical part of an application as a database but still it's a very popular templating language and needs performance!

**Comment by fabpot** [comment]
Having the Twig C extension by default would indeed be a great booster for any app using Twig. What do you think @dzuelke?

**Comment by phansys** [comment]
:+1:

**Comment by kbond** [comment]
+1

**Comment by phansys** [comment]
@dzuelke, is there something missing in this PR to get merged? Please, let us know in order to do any required update.

**Comment by seb0zz** [comment]
@dzuelke are you planning to give any feedback on community requests or do you want to keep ignoring them? -.-

**Comment by dzuelke** [comment]
Will wait with merging at least until PHP 7 is supported in `ext-twig`. Can you, before or after that happens, please rebuild this PR using the new package infrastructure (see #104)?

**Comment by buschjost** [comment]
I am sorry I will not be able to. We moved away from Heroku already.

**Pull request closed without merging**
