### PR TITLE
Update buildpack image to align with marketing

### PR DESCRIPTION
**Pull request by mattgraham**
php

### CODE REVIEW

**Comment by dzuelke** [comment]
> Can we update the actual version to v231 or above? Happy to open a separate PR?

@ivvvve what are you referring to?

**Review by edmorley — COMMENTED** [review]
(switching the code review request from the team alias to the PHP language owner)

**Comment by schneems** [comment]
I like this image more than the current one. I think we should merge this or close it instead of leaving it open.

**Review by dzuelke — APPROVED** [review]

**Comment by dzuelke** [comment]
Goodbye, ElePHPant!

**Pull request merged**
