### PR TITLE
Release PHP 7.3.33, 7.4.26 and 8.0.13

### PR DESCRIPTION
**Pull request by edmorley**
https://www.php.net/ChangeLog-7.php#7.3.33
https://www.php.net/ChangeLog-7.php#7.4.26
https://www.php.net/ChangeLog-8.php#8.0.12

GUS-W-10196297.

### CODE REVIEW

**Review by joshwlewis — APPROVED** [review]

**Comment by edmorley** [comment]
Builds for 2 stacks x 4 runtimes completed, mkrepo run and then synced to stable, using the process at:
https://github.com/heroku/languages-team/blob/main/languages/php/platform.md

**Comment by edmorley** [comment]
https://devcenter.heroku.com/admin/articles/diff/2021/2021v216..2021v217
https://devcenter.heroku.com/articles/php-support#available-versions

https://devcenter.heroku.com/changelog-items/2295

**Comment by edmorley** [comment]
```
$ heroku buildpacks:publish heroku/php v201
Two-factor code: ********************************************
Publishing buildpack heroku/php... done
Publishing buildpack was successful

$ heroku buildpacks:versions heroku/php | head -n3
Version  Released At               Status
───────  ────────────────────────  ─────────
199      2021-11-18T19:36:58.527Z  published
```

**Comment by edmorley** [comment]
https://direwolf.herokai.com/#/runs/2b6df4b3-e3a3-4525-bf72-6186e08e08d1

**Pull request merged**
